---
title: "Data Import"
author: "Lu Chen"
date: "09/17/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## load in a dataset

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv") #read_csv would guess the type of your coloumn
litters_data = janitor::clean_names(litters_data) #use the janitor package to clean up the single quotation mark and Upper case in the variable names
```

#load in pup data

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

#read in an excel file

```{r}
mlb11_data = 
  read_excel(
    path = "./data/mlb11.xlsx")
    #range = "A1:D7"

#write_csv(mlb11_data_subset, path = "./data/mlb1_subset")
```
#read in SAS
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")

```

##Selecting!!

```{r}
select(litters_data, group, litter_number) #first item:where the data selected from, and following with the column you want to selected

select(litters_data, litter_number, gd0_weight, starts_with("pups")) #start_with phase helps us to select columns which the name starting with pups

select(litters_data, litter_number, group, everything()) #take the litter_number and group first, and then anything else

select(litters_data, -group) #-group helps to exclude the column you dont want

select(litters_data, litter_number, gd0_weight:pups_born_alive) #includes every column starting with gd0_weight upto pup_born_alive

select(litters_data, GROUP = group, litter_number) #rename the "group" to "GROUP"

rename(litters_data, GROUP = group) #only rename the column, not doing the selection
```

## Filtering!!
```{r}
filter(litters_data, group == "Mod8") #double equal sign: to chech whether the group is equal to con7/Mod 8 

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >=20)

filter(litters_data, pups_born_alive <6)

filter(litters_data, pups_born_alive <6, group == "Con7") #filter the dataset even more
```

