---
title: "new_tidyr_version"
author: "Lu Chen"
date: "09/24/2019"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

#wide to long
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
  pivot_longer(
  pulse_data,
  bdi_score_bl:bdi_score_12m,
  names_to = "visit", #creating a new column containing bdi data
  names_prefix = "bdi_score_",
  values_to = "bdi" #
) %>% 
  mutate(
    visit = recode(visit, "bl" = "00m") #change/set the value of bl in visit column into "00m"
  )
```

#seperate in litters
```{r}
litters_data = 
  read.csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(col = group, into = c("dose", "day_of_tx"),3) #seperate the old column "group" into two new columns dose and day_of_tx;

```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

pivot_wider(
  #pivot_longer: transfer long format to wide format
  analysis_result,
  names_from = time,
  values_from = mean
)
```

###bind rows

```{r}
fellowship_data = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_data = 
  bind_rows(fellowship_data, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  select(movie, race, sex, words)

```

### join datasets
```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) #recoding the numerical variable to categorical variable

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))

```

try to join these datasets!!

```{r}
fas_data = 
  left_join(pup_data, litter_data, by = "litter_number") #by: the joining variable;the left_join statement is clear, if you do not specify which variable you want to join by, it will auto-join with the variable the system picked;

  full_join(pup_data, litter_data, by = "litter_number") %>% filter(is.na(sex))
```




